apiVersion: v1
kind: Service
metadata:
  name: wishpool-web
  namespace: wishpool
  labels:
    app.kubernetes.io/name: wishpool-web
    app.kubernetes.io/part-of: wishpool
spec:
  selector:
    app.kubernetes.io/name: wishpool-web
  ports:
    - name: http
      port: 80
      targetPort: http
